use crate::presets::{Crop, Dither, Format, ImageCodec, Preset, ProResProfile};

pub fn default_presets() -> Vec<Preset> {
    vec![
        // GIF presets — mirror existing SendTo_FFmpeg scripts
        Preset {
            id: "gif_420_lq_20".into(),
            name: "GIF 420px LQ 20fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_420px_LQ_20fps".into(),
            width: Some(420),
            height: None,
            fps: Some(20),
            crop: None,
            palette_colors: Some(96),
            dither: Some(Dither::Bayer),
            bayer_scale: Some(3),
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 0,
        },
        Preset {
            id: "gif_500_mq_25".into(),
            name: "GIF 500px MQ 25fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_500px_MQ_25fps".into(),
            width: Some(500),
            height: None,
            fps: Some(25),
            crop: None,
            palette_colors: Some(128),
            dither: Some(Dither::Bayer),
            bayer_scale: Some(3),
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 1,
        },
        Preset {
            id: "gif_800_hq_30".into(),
            name: "GIF 800px HQ 30fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_800px_HQ_30fps".into(),
            width: Some(800),
            height: None,
            fps: Some(30),
            crop: None,
            palette_colors: Some(192),
            dither: Some(Dither::Sierra24a),
            bayer_scale: None,
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 3,
        },
        // MP4 presets — sizing
        Preset {
            id: "mp4_720p".into(),
            name: "MP4 720p".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_720p".into(),
            width: Some(1280),
            height: Some(720),
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: Some(23),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 4,
        },
        Preset {
            id: "mp4_720p_10mb".into(),
            name: "MP4 720p · 10 MB".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_720p_10mb".into(),
            width: Some(1280),
            height: Some(720),
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            // CRF here is a fallback only — when target_max_mb is set,
            // the encoder computes an explicit bitrate from clip
            // duration and ignores CRF. Leaving it at a quality-band
            // value (not 23 default) keeps short clips from blowing
            // through the budget when the bitrate calculation would
            // otherwise pick something silly-low.
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: Some(10),
            image_codec: None,
            image_quality: None,
            strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 5,
        },
        // MP4 presets — cropping
        Preset {
            id: "mp4_crop_9x16".into(),
            name: "MP4 → 9:16 (crop)".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_9x16".into(),
            width: None,
            height: None,
            fps: None,
            crop: Some(Crop::V9x16),
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 8,
        },

        // ---- ProRes presets ----
        // Two tiers ship because they answer different questions:
        // 422 HQ is "give me an editable intermediate", 4444 is "keep
        // my alpha". Everything else (Proxy / LT / 422 / 4444 XQ) is a
        // dropdown away on a copy of either one.
        //
        // No width / height / fps: a mastering format that silently
        // resized its input would be worse than useless.
        Preset {
            id: "prores_422_hq".into(),
            name: "ProRes 422 HQ".into(),
            enabled: true,
            format: Format::ProRes,
            suffix: "_prores_hq".into(),
            width: None,
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            // CRF / preset-speed / bitrate are all meaningless for
            // ProRes — the profile is the only quality control.
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            image_codec: None,
            image_quality: None,
            strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: Some(ProResProfile::Hq),
            icon: None,
            order: 9,
        },
        Preset {
            id: "prores_4444_alpha".into(),
            name: "ProRes 4444 (alpha)".into(),
            enabled: true,
            format: Format::ProRes,
            suffix: "_prores_4444".into(),
            width: None,
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            image_codec: None,
            image_quality: None,
            strip_metadata: None,
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: Some(ProResProfile::P4444),
            icon: None,
            order: 10,
        },

        // ---- Image presets ----
        // Order 20+ keeps them grouped below the video presets in the
        // sidebar but doesn't fight with user-added presets at order 0.
        Preset {
            id: "img_reduce_size".into(),
            name: "Reduce Size".into(),
            enabled: true,
            format: Format::Image,
            suffix: "_reduced".into(),
            width: None,
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            image_codec: Some(ImageCodec::Png),
            image_quality: Some(6),
            strip_metadata: Some(true),
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 19,
        },
        Preset {
            id: "img_jpeg_85".into(),
            name: "JPEG 85% (web, strip EXIF)".into(),
            enabled: true,
            format: Format::Image,
            suffix: "_q85".into(),
            width: None,
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            image_codec: Some(ImageCodec::Jpeg),
            image_quality: Some(85),
            strip_metadata: Some(true),
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 20,
        },
        Preset {
            id: "img_thumb_512".into(),
            name: "Thumbnail 512px PNG".into(),
            enabled: true,
            format: Format::Image,
            suffix: "_thumb".into(),
            width: Some(512),
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            loop_mode: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            image_codec: Some(ImageCodec::Png),
            image_quality: Some(6),
            strip_metadata: Some(true),
            grayscale: None,
            timecode: None,
            guides: None,
            overlay: None,
            crop_rect: None,
            modify_flip_h: None,
            modify_flip_v: None,
            modify_reverse: None,
            modify_overwrite: None,
            modify_remove_audio: None,
            modify_rotate: None,
            modify_trim_start_sec: None,
            modify_trim_end_sec: None,
            modify_speed: None,
            speed: None,
            modify_interp: None,
            watermark: None,
            prores_profile: None,
            icon: None,
            order: 23,
        },
    ]
}

pub fn default_custom() -> Preset {
    Preset {
        id: "custom".into(),
        name: "Custom".into(),
        enabled: false,
        format: Format::Gif,
        suffix: "_custom".into(),
        width: Some(500),
        height: None,
        fps: Some(24),
        crop: None,
        palette_colors: Some(128),
        dither: Some(Dither::Bayer),
        bayer_scale: Some(3),
        loop_mode: None,
        crf: Some(23),
        preset_speed: Some("medium".into()),
        video_bitrate: None,
        audio_bitrate: Some("128k".into()),
        use_cuda: Some(false),
        target_max_mb: None,
        image_codec: None,
        image_quality: None,
        strip_metadata: None,
        grayscale: None,
        timecode: None,
        guides: None,
        overlay: None,
        crop_rect: None,
        modify_flip_h: None,
        modify_flip_v: None,
        modify_reverse: None,
        modify_overwrite: None,
        modify_remove_audio: None,
        modify_rotate: None,
        modify_trim_start_sec: None,
        modify_trim_end_sec: None,
        modify_speed: None,
        speed: None,
        modify_interp: None,
        watermark: None,
        prores_profile: None,
        icon: None,
        order: 0,
    }
}
